# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brownbag',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
