# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170324_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brownbag',
            name='date',
            field=models.DateField(),
        ),
    ]
