# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_brownbag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SecretSanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('giftee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('santa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='santa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
