# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170909_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretsanta',
            name='giftee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftee', to=settings.AUTH_USER_MODEL),
        ),
    ]
