# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_hangout_secretsanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHangout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hangout')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
