# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170211_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brownbag',
            field=models.CharField(choices=[('NEXT IN LINE', 'next_in_line'), ('DONE', 'done'), ('NOT DONE', 'not_done')], default='NOT DONE', max_length=12),
        ),
    ]
