# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_brownbag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brownbag',
            name='status',
            field=models.CharField(choices=[('NEXT IN LINE', 'next_in_line'), ('DONE', 'done'), ('NOT DONE', 'not_done')], default='NOT DONE', max_length=12),
        ),
    ]
