# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170212_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brownbag',
            name='status',
            field=models.CharField(choices=[('next_in_line', 'Next In Line'), ('done', 'Done'), ('not_done', 'Not Done')], default='not_done', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brownbag',
            field=models.CharField(choices=[('next_in_line', 'Next In Line'), ('done', 'Done'), ('not_done', 'Not Done')], default='not_done', max_length=12),
        ),
    ]
